server:
  port: 3344
spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          # GitHub上面的git仓库https地址
          uri: https://github.com/tangwenjun666/cloud-carinsurance-config.git
    ###开始配置consul的服务注册
    consul:
      #consul服务器的主机地址
      host: localhost
      #consul服务器的ip地址
      port: 8500
      discovery:
        #服务主机名称
        #hostname: 127.0.0.1
        #服务的名称
        service-name: ${spring.application.name}
        #是否需要注册
        register: true